language: node_js # node环境
node_js:
  - lts/*
script:
  - npm run docs:build # 执行命令
notifications:
  webhooks:
    urls:
      - https://oapi.dingtalk.com/robot/send?access_token=abfb2b48ea8c94a692c416175ca2d415b90f26aac39d5e552d171868c91ab4c3
    on_success: always # default: always
    on_failure: always # default: always
    on_start: change # default: never
    on_cancel: always # default: always
    on_error: always # default: always
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: docs # 部署的文件夹文件
  github-token: $GITHUB_TOKEN # travis服务上的token变量
  target-branch: gh-pages # 集成发布到gh-pages上
  keep-history: true
  on:
    branch: master
